# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TravelTracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

	pod 'React', :path => '../node_modules/react-native'
	pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
	pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

end
